name: Get version
description: Get the version of the current repository
inputs:
  version_file:
    description: 'Version file'
    required: false
    default: 'version.json'
outputs:
  version:
    description: 'Version'
runs:
  using: 'composite'
  steps:
    - name: Get release version
      if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main')
      shell: bash
      run: |
        echo "version=$(jq -r .version ${{ inputs.version_file }})-${{ github.run_number }}" >> $GITHUB_OUTPUT
    - name: Get feature version
      if: github.ref != 'refs/heads/main' && github.event_name != 'pull_request'
      shell: bash
      run: |
        echo "version=DEV.${{ github.run_number }}" >> $GITHUB_OUTPUT
    