name: Get version
description: Populates the IMAGE_VERSION environment variable with the version of the image being built
inputs:
  version_file:
    description: 'Version file'
    required: false
    default: 'version.json'
runs:
  using: 'composite'
  steps:
    - name: Get release version
      if: github.ref == 'refs/heads/main' || github.event.pull_request || github.event_name == 'schedule'
      shell: bash
      run: |
        echo "IMAGE_VERSION=$(jq -r .version ${{ inputs.version_file }})-${{ github.run_number }}" >> $GITHUB_ENV
    - name: Get feature version
      if: github.ref != 'refs/heads/main' && github.event_name != 'schedule' && !github.event.pull_request
      shell: bash
      run: |
        echo "IMAGE_VERSION=DEV.${{ github.run_number }}" >> $GITHUB_ENV
    